- name: Install required packages
  apt: pkg={{item}}
  with_items:
    - build-essential
    - zlib1g-dev
    - libyaml-dev
    - libssl-dev
    - libgdbm-dev
    - libreadline-dev
    - libncurses5-dev
    - libffi-dev
    - curl
    - openssh-server
    - redis-server
    - checkinstall
    - libxml2-dev
    - libxslt-dev
    - libcurl4-openssl-dev
    - libicu-dev
    - logrotate
    - python-docutils
    - git-core
    - expect

- include: ruby.yml
- include: database.yml

- name: Clone GitLab repo
  git:
    repo={{ gitlab_repo_url }}
    dest={{ gitlab_repo_dir }}
    version=7-0-stable
    update=no

- name: Make sure gitlab user owns the repo directory
  file: path={{gitlab_repo_dir}} owner=git recurse=yes state=directory

- name: Update gitlab configuration
  template:
    src=gitlab-config.j2
    dest="{{gitlab_repo_dir}}/config/gitlab.yml"
    owner={{gitlab_user}}

- name: Make sure the gitlab user has ownership of the log directory
  file: path={{gitlab_repo_dir}}/log
    owner={{gitlab_user}}
    recurse=yes
    state=directory
    mode=0744

- name: Make sure the gitlab user has ownership of the tmp directory
  file:
    path={{gitlab_repo_dir}}/tmp
    owner={{gitlab_user}}
    recurse=yes
    state=directory
    mode=0744

- name: Make sure gitlab user can write to tmp/pids/
  file: path={{gitlab_repo_dir}}/tmp/pids/
    mode=0744

- name: Make sure gitlab user can write to tmp/sockests
  file: path={{gitlab_repo_dir}}/tmp/sockets/
    mode=0744

- name: Make sure satellites directory exists
  file: path={{gitlab_satellites_dir}} state=directory
    owner={{gitlab_user}}

- name: Make sure gitlab user can write to public/uploads directory
  file: path={{gitlab_repo_dir}}/public/uploads state=directory mode=0744

- name: Update unicorn config
  template:
    src=unicorn.rb.j2
    dest={{gitlab_repo_dir}}/config/unicorn.rb
    owner={{gitlab_user}}

- name: Copy Rack attack config
  copy:
    src=rack_attack.rb
    dest={{gitlab_repo_dir}}/config/initializers/rack_attack.rb
    owner={{gitlab_user}}

- name: Configure git
  template: src=gitconfig.j2 dest=/home/{{gitlab_user}}/.gitconfig owner={{gitlab_user}}

- name: Configure database
  template:
    src=database.j2
    dest={{gitlab_repo_dir}}/config/database.yml
    owner={{gitlab_user}}
    mode=0700

# NOTE: For some reason, the gem module is not successfully installing bunder,
# so just use the command module
- name: Install bundler
  command: "gem install bundler"

# NOTE: The option says "without mysql"
- name: Install gems
  command: "sudo -u {{gitlab_user}} -H bundle install --deployment --without development test mysql aws"
  args:
    chdir: "{{gitlab_repo_dir}}"

- name: Install GitLab Shell
  command: "sudo -u {{gitlab_user}} -H bundle exec rake gitlab:shell:install[v1.9.6] REDIS_URL={{gitlab_redis_url}} RAILS_ENV=production"
  args:
    chdir: "{{gitlab_repo_dir}}"


- name: Update gitlab-shell configuration
  template: src=gitlab-shell-config.j2 dest={{gitlab_shell_dir}}/config.yml owner={{gitlab_user}}

- name: Check if database has already been initialized
  command: sudo -u git -H psql -d gitlabhq_production -c "\dt"
  register: gitlab_database_check

# - debug: var=gitlab_database_check

# ONLY run this once! This will check if the database is already initialized (by checking the
# existence of the web_hooks table)
- name: Initialize database and activate advanced features
  command: sudo -u {{gitlab_user}} -H bundle exec rake gitlab:setup RAILS_ENV=production force={{gitlab_force_db}}
  args:
    chdir: "{{gitlab_repo_dir}}"
  when: '"web_hooks" not in gitlab_database_check.stdout'


- name: Install init script
  command: cp {{gitlab_repo_dir}}/lib/support/init.d/gitlab /etc/init.d/gitlab
  args:
    creates: /etc/init.d/gitlab

- name: Update init defaults
  template: src="init_defaults.j2" dest="/etc/default/gitlab"


- name: Make gitlab start on boot
  command: update-rc.d gitlab defaults 21
  sudo: yes


- name: Set up logrotate
  command: cp {{gitlab_repo_dir}}/lib/support/logrotate/gitlab /etc/logrotate.d/gitlab
  args:
    creates: /etc/logrotate.d/gitlab

- name: Compile assets
  command: sudo -u git -H bundle exec rake assets:precompile RAILS_ENV=production
  args:
    chdir: "{{gitlab_repo_dir}}"
  notify: restart gitlab

- name: Install nginx
  apt: pkg=nginx state=present

- name: Copy gitlab nginx site config
  template: src=nginx-gitlab.j2 dest=/etc/nginx/sites-available/gitlab

- name: Link gitlab site config
  file: src=/etc/nginx/sites-available/gitlab dest=/etc/nginx/sites-enabled/gitlab state=link
  notify: restart nginx

- name: Make sure postfix is uninstalled
  apt: pkg=postfix state=absent
