# variables
docker_scrapi_source_branch: master
docker_scrapi_source_repo: https://github.com/CenterForOpenScience/scrapi.git

# apiserver
docker_scrapi_apiserver: no
docker_scrapi_apiserver_name: scrapi_apiserver_1
docker_scrapi_apiserver_image: centerforopenscience/scrapi:3.5
docker_scrapi_apiserver_command: "uwsgi --ini /etc/uwsgi/uwsgi.ini"
docker_scrapi_apiserver_source_conf_file: apiserver/uwsgi.ini
docker_scrapi_apiserver_conf_dir: /opt/scrapi_apiserver/conf
docker_scrapi_apiserver_conf_file: "{{ docker_scrapi_apiserver_conf_dir }}/uwsgi.ini"
docker_scrapi_apiserver_env:
  SOURCE_BRANCH: "{{ docker_scrapi_source_branch }}"
  SOURCE_REPO: "{{ docker_scrapi_source_repo }}"
docker_scrapi_apiserver_net: bridge
docker_scrapi_apiserver_hostname: "{{ hostname_name }}"
docker_scrapi_apiserver_expose:
  - 8000
docker_scrapi_apiserver_ports: []
docker_scrapi_apiserver_links: []
docker_scrapi_apiserver_volumes:
  - "{{ docker_scrapi_apiserver_conf_file }}:/etc/uwsgi/uwsgi.ini"
docker_scrapi_apiserver_volumes_from: []

# celery beat
docker_scrapi_celery_beat: no
docker_scrapi_celery_beat_instances: 1
docker_scrapi_celery_beat_name: scrapi_celery_beat
docker_scrapi_celery_beat_image: centerforopenscience/scrapi:3.5
docker_scrapi_celery_beat_command: "gosu www-data invoke beat"
docker_scrapi_celery_beat_env:
  SOURCE_BRANCH: "{{ docker_scrapi_source_branch }}"
  SOURCE_REPO: "{{ docker_scrapi_source_repo }}"
docker_scrapi_celery_beat_net: bridge
docker_scrapi_celery_beat_hostname: "{{ hostname_name }}"
docker_scrapi_celery_beat_expose: []
docker_scrapi_celery_beat_ports: []
docker_scrapi_celery_beat_links: []
docker_scrapi_celery_beat_volumes: []
docker_scrapi_celery_beat_volumes_from: []

# celery worker
docker_scrapi_celery_worker: no
docker_scrapi_celery_worker_instances: 2
docker_scrapi_celery_worker_name: scrapi_celery_worker
docker_scrapi_celery_worker_image: centerforopenscience/scrapi:3.5
docker_scrapi_celery_worker_command: "gosu www-data invoke worker --hostname=worker{{ item }}.%h"
docker_scrapi_celery_worker_env:
  SOURCE_BRANCH: "{{ docker_scrapi_source_branch }}"
  SOURCE_REPO: "{{ docker_scrapi_source_repo }}"
docker_scrapi_celery_worker_net: bridge
docker_scrapi_celery_worker_hostname: "{{ hostname_name }}"
docker_scrapi_celery_worker_expose: []
docker_scrapi_celery_worker_ports: []
docker_scrapi_celery_worker_links: []
docker_scrapi_celery_worker_volumes: []
docker_scrapi_celery_worker_volumes_from: []
