---
- include: dependencies.yml
- include: user.yml
- include: package_install.yml
- include: configure.yml

#- include: default.yml
#  when: nginx_setup_default == true
#- include: monit.yml
#  when: monit_protection == true

#- name: Ensure Nginx is at the desired version
#  apt: pkg=nginx state=latest
#- name: Ensure main Nginx configuration file is up to date
#  template: src=nginx.conf dest=/etc/nginx/nginx.conf
#  notify: restart nginx
#- name: Ensure Nginx does not have a default configuration
#  file: path=/etc/nginx/sites-enabled/default state=absent
#  notify: restart nginx
