- name: Nginx | Add the nginx apt key
  apt_key: id=7BD9BF62 url=http://nginx.org/keys/nginx_signing.key
  sudo: yes

- name: Nginx | Add the nginx repo to the apt sources
  apt_repository: repo='deb http://nginx.org/packages/ubuntu saucy nginx'
  sudo: yes

- include: commons.yml
  sudo: yes

- name: Nginx | Make sure nginx is installed
  apt: pkg=nginx
  sudo: yes
  notify:
    - restart nginx