# file: roles/common/meta/main.yml

dependencies:
  - { role: Ansibles.hostname }
  - { role: Ansibles.timezone }
  - { role: directories }
  - { role: Ansibles.apt }
  - { role: vim }
  - { role: Ansibles.build-essential }
  - { role: Ansibles.cron }
  - { role: ssh }
