- name: Ensure docker scrapi beat logrotate config
  template:
    src: "{{ docker_scrapi_beat_log_rotate_source_file }}"
    dest: "/etc/logrotate.d/{{ docker_scrapi_beat_log_rotate_file }}"
    owner: root
    group: root
    mode: 0644
  tags:
    - install
    - settings


- name: Ensure docker scrapi beat directories exist
  sudo: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_scrapi_beat_conf_dir }}"
    - "{{ docker_scrapi_beat_log_dir }}"
  tags:
    - install
    - upgrade


- name: Copy docker scrapi beat configuration settings
  copy:
    src: "{{ docker_scrapi_beat_source_conf_file }}"
    dest: "{{ docker_scrapi_beat_conf_file }}"
    mode: 0660
  tags:
    - install
    - settings
    - upgrade


- name: Restart docker scrapi beat container
  sudo: yes
  shell: "docker restart {{ docker_scrapi_beat_name }}"
  tags:
    - restart


- name: Run docker scrapi beat container
  docker:
    command: "/bin/bash -c 'invoke beat 2>&1 | tee -a /log/{{ docker_scrapi_beat_name }}.log'"
    env: "{{ docker_scrapi_beat_env }}"
    expose: "{{ docker_scrapi_beat_expose }}"
    hostname: "{{ hostname_name }}"
    image: "centerforopenscience/scrapi:latest"
    links: "{{ docker_scrapi_beat_links }}"
    name: "{{ docker_scrapi_beat_name }}"
    ports: "{{ docker_scrapi_beat_ports }}"
    restart_policy: always
    state: running
    volumes: "{{ docker_scrapi_beat_volumes }}"
  tags:
    - install
    - upgrade
