- name: Restart docker scrapi beat container
  sudo: yes
  shell: "docker restart {{ docker_scrapi_celery_beat_name }}"
  tags:
    - restart


- name: Run docker scrapi beat container
  docker:
    command: "invoke beat"
    env: "{{ docker_scrapi_celery_beat_env }}"
    expose: "{{ docker_scrapi_celery_beat_expose }}"
    hostname: "{{ docker_scrapi_celery_beat_hostname }}"
    image: "{{ docker_scrapi_image }}"
    links: "{{ docker_scrapi_celery_beat_links }}"
    name: "{{ docker_scrapi_celery_beat_name }}"
    ports: "{{ docker_scrapi_celery_beat_ports }}"
    pull: always
    restart_policy: always
    state: reloaded
    volumes_from: "{{ docker_scrapi_celery_beat_volumes_from }}"
  tags:
    - install
    - upgrade
