- include: server.yml
  when: docker_scrapi_server

- include: worker.yml
  when: docker_scrapi_worker

- include: beat.yml
  when: docker_scrapi_beat

- include: apiserver.yml
  when: docker_scrapi_apiserver

- include: uwsgi.yml
  when: docker_apiserver_uwsgi
