- include: worker.yml
  when: docker_scrapi_celery_worker

- include: beat.yml
  when: docker_scrapi_celery_beat

- include: apiserver.yml
  when: docker_scrapi_apiserver

- include: uwsgi.yml
  when: docker_scrapi_uwsgi
