- name: Ensure docker scrapi worker logrotate config
  template:
    src: "{{ docker_scrapi_worker_log_rotate_source_file }}"
    dest: "/etc/logrotate.d/{{ docker_scrapi_worker_log_rotate_file }}"
    owner: root
    group: root
    mode: 0644
  tags:
    - install
    - settings


- name: Ensure docker scrapi worker directories exist
  sudo: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_scrapi_worker_conf_dir }}"
    - "{{ docker_scrapi_worker_log_dir }}"
  tags:
    - install
    - upgrade


- name: Copy docker scrapi worker configuration settings
  copy:
    src: "{{ docker_scrapi_worker_source_conf_file }}"
    dest: "{{ docker_scrapi_worker_conf_file }}"
    mode: 0660
  tags:
    - install
    - settings
    - upgrade


- name: Restart docker scrapi worker container
  sudo: yes
  shell: "docker restart {{ docker_scrapi_worker_name }}_{{ item }}"
  with_sequence: count={{ docker_scrapi_worker_instances }}
  when: docker_scrapi_worker_instances > 0
  tags:
    - restart


- name: Run docker scrapi worker container
  docker:
    command: '/bin/bash -c "invoke worker 2>&1 | tee -a /log/{{ docker_scrapi_worker_name }}_{{ item }}.log"'
    env: "{{ docker_scrapi_worker_env }}"
    expose: "{{ docker_scrapi_worker_expose }}"
    hostname: "{{ hostname_name }}-worker{{ item }}"
    image: "centerforopenscience/scrapi:latest"
    links: "{{ docker_scrapi_worker_links }}"
    name: "{{ docker_scrapi_worker_name }}_{{ item }}"
    ports: "{{ docker_scrapi_worker_ports }}"
    restart_policy: always
    state: running
    volumes: "{{ docker_scrapi_worker_volumes }}"
  with_sequence: count={{ docker_scrapi_worker_instances }}
  when: docker_scrapi_worker_instances > 0
  tags:
    - install
    - upgrade
