
- name: Ensure /etc/sudoers.d directory is present
  file: path=/etc/sudoers.d state=directory

- name: Ensure /etc/sudoers.d is scanned by sudo
  action: lineinfile dest=/etc/sudoers regexp="#includedir\s+/etc/sudoers.d" line="#includedir /etc/sudoers.d"

- name: Add jenkins to the sudoers
  action: 'lineinfile dest=/etc/sudoers.d/jenkins state=present create=yes regexp="jenkins .*" line="jenkins ALL=(ALL) NOPASSWD: /usr/bin/docker"'

- name: Ensure /etc/sudoers.d files have correct permissions
  action: file path=/etc/sudoers.d/jenkins mode=0440 state=file owner=root group=root