- name: Ensure docker osf logrotate config
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/elasticsearch
    owner: root
    group: root
    mode: 0644
  tags:
    - install
    - settings


- name: Restart docker elasticsearch container
  sudo: yes
  shell: "docker restart {{ docker_elasticsearch_name }}"
  tags:
    - restart


- name: Ensure docker elasticsearch directories exist
  sudo: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_elasticsearch_conf_dir }}"
    - "{{ docker_elasticsearch_data_dir }}"
    - "{{ docker_elasticsearch_log_dir }}"
  tags:
    - install
    - upgrade


- name: Copy docker elasticsearch configuration settings
  copy:
    src: "conf/"
    dest: "{{ docker_elasticsearch_conf_dir }}/"
    mode: 0660
  tags:
    - install
    - settings
    - upgrade


- name: Run docker elasticsearch container
  docker:
    name: "{{ docker_elasticsearch_name }}"
    state: running
    hostname: "{{ hostname_name }}-elasticsearch"
    restart_policy: always
    image: "elasticsearch:latest"
    expose: "{{ docker_elasticsearch_expose }}"
    ports: "{{ docker_elasticsearch_ports }}"
    env: "{{ docker_elasticsearch_env }}"
    env:
      ES_HEAP_SIZE: "{{ (ansible_memtotal_mb / 2) | int }}m"
    volumes:
      - "{{ docker_elasticsearch_conf_dir }}:/usr/share/elasticsearch/config"
      - "{{ docker_elasticsearch_data_dir }}:/usr/share/elasticsearch/data"
      - "{{ docker_elasticsearch_log_dir }}:/usr/share/elasticsearch/logs"
  tags:
    - install
    - upgrade
