

- name: Install uwsgi apt dependencies
  apt: pkg="{{ item }}" state="present"
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - libxml2-dev

- name: Install uwsgi with pip
  pip: name="uwsgi" version="{{ uwsgi_version }}"
  when: uwsgi_install_mode == 'pip'

- name: Install uwsgi with apt
  apt: name="uwsgi" state=present
  when: uwsgi_install_mode == 'apt'

- name: Ensure /etc/uwsgi/apps-available exists
  file: path=/etc/uwsgi/apps-available state=directory mode=0751 group=www-data owner=www-data

- name: Ensure /etc/uwsgi/apps-enabled exists
  file: path=/etc/uwsgi/apps-enabled state=directory mode=0751 group=www-data owner=www-data

- name: Update uwsgi.conf script
  copy: src="uwsgi.conf" dest="/etc/init/uwsgi.conf"
