- name: Set up directory of repositories
  hosts: all
  pre_tasks:
    - fail: msg="One or more tags must be specified to run this playbook"
  vars:
    docker_env: test

    docker_storage: no
    docker_storage_name: "{{ docker_env }}_scrapi_storage_1"
    docker_storage_dir: "/opt/{{ docker_env }}_scrapi_storage/"
    docker_storage_conf_dir: "{{ docker_storage_dir }}conf/"
    docker_storage_copy_ops:
      - src: "{{ docker_storage_source_conf_dir }}"
        dest: "{{ docker_storage_conf_dir }}"
    docker_storage_file_ops:
      - state: directory
        path: "{{ docker_storage_dir }}code"
        mode: 644
        owner: www-data
        group: www-data
    docker_storage_volumes:
      - "{{ docker_storage_conf_dir }}code/:/code:rw"
      - "{{ docker_storage_conf_dir }}local.py:/code/scrapi/settings/local.py:ro"
      - "{{ docker_storage_conf_dir }}local2.py:/code/api/api/settings/local.py:ro"

    docker_postgres: no
    docker_postgres_conf_dir: "/opt/{{ docker_env }}_scrapi_postgres/conf/"
    docker_postgres_data_dir: "/opt/{{ docker_env }}_scrapi_postgres/data/"
    docker_postgres_name: "{{ docker_env }}_scrapi_postgres_1"
    docker_postgres_env:
      POSTGRES_DB: "scrapi_{{ docker_env }}"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    docker_dor_server_name: "{{ docker_env }}_dor_server_1"
    docker_dor_server_conf_dir: "/opt/{{ docker_env }}_dor_server/conf/"
    docker_dor_server_env:
      UPDATE_CMD: "invoke wheelhouse && invoke requirements && gosu www-data python manage.py collectstatic --noinput"
      SOURCE_BRANCH: "{{ docker_dor_source_branch }}"
      SOURCE_REPO: "{{ docker_dor_source_repo }}"
    docker_dor_server_links: []
    docker_dor_server_volumes_from:
      - "{{ docker_storage_name }}"

    docker_nginx: no
    docker_nginx_name: "{{ docker_env }}_scrapi_nginx_1"
    docker_nginx_image: centerforopenscience/nginx:1 # auto reload on /etc/hosts change
    docker_nginx_conf_dir: "/opt/{{ docker_env }}_scrapi_nginx/conf/"
    docker_nginx_expose:
      - 80
      - 443
    docker_nginx_links:
      - "{{ docker_scrapi_server_name }}:server"
    docker_nginx_volumes_from:
      - "{{ docker_storage_name }}"
  roles:
    - role: docker-storage
      when: docker_storage

    - role: docker-postgres
      when: docker_postgres

    - role: docker-dor

    - role: docker-nginx
      when: docker_nginx
