- name: Set up scrapi
  hosts: all
  pre_tasks:
    - fail: msg="One or more tags must be specified to run this playbook"
  vars:
    docker_env: test

    docker_storage: no
    docker_storage_name: "{{ docker_env }}_scrapi_storage_1"
    docker_storage_dir: "/opt/{{ docker_env }}_scrapi_storage/"
    docker_storage_conf_dir: "{{ docker_storage_dir }}conf/"
    docker_storage_copy_ops:
      - src: "{{ docker_storage_source_conf_dir }}"
        dest: "{{ docker_storage_conf_dir }}"
    docker_storage_file_ops:
      - state: directory
        path: "{{ docker_storage_dir }}code"
        mode: 644
        owner: www-data
        group: www-data
    docker_storage_volumes:
      - "{{ docker_storage_conf_dir }}code/:/code:rw"
      - "{{ docker_storage_conf_dir }}local.py:/code/scrapi/settings/local.py:ro"
      - "{{ docker_storage_conf_dir }}local2.py:/code/api/api/settings/local.py:ro"

    docker_elasticsearch: no
    docker_elasticsearch_name: "{{ docker_env }}_scrapi_elasticsearch_1"
    docker_elasticsearch_conf_dir: "/opt/{{ docker_env }}_scrapi_elasticsearch/conf"
    docker_elasticsearch_data_dir: "/opt/{{ docker_env }}_scrapi_elasticsearch/data"
    docker_elasticsearch_expose:
      - 9200

    docker_cassandra: no
    docker_cassandra_name: "{{ docker_env }}_scrapi_cassandra_1"
    docker_cassandra_data_dir: "/opt/{{ docker_env }}_scrapi_cassandra/data"
    docker_cassandra_env: {}
    docker_cassandra_expose:
      - 9160
    docker_cassandra_ports: []

    docker_postgres_repmgr: no
    docker_postgres_repmgr_source_conf_file: roles/docker-scrapi/files/repmgr.conf
    docker_postgres_repmgr_conf_dir: "/opt/{{ docker_env }}_scrapi_postgres/conf"
    docker_postgres_repmgr_data_dir: "/opt/{{ docker_env }}_scrapi_postgres/data"
    docker_postgres_repmgr_name: "{{ docker_env }}_scrapi_postgres_1"
    docker_postgres_repmgr_env:
      POSTGRES_DB: "scrapi_{{ docker_env }}"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    docker_rabbitmq: no
    docker_rabbitmq_name: "{{ docker_env }}_scrapi_rabbitmq_1"
    docker_rabbitmq_data_dir: "/opt/{{ docker_env }}_scrapi_rabbitmq/data"

    docker_fluentd: no
    docker_fluentd_name: "{{ docker_env }}_scrapi_fluentd_1"
    docker_fluentd_source_conf_dir: roles/docker-scrapi/files/fluentd/
    docker_fluentd_conf_dir: "/opt/{{ docker_env }}_scrapi_fluentd/conf"
    docker_fluentd_conf_file: "{{ docker_fluentd_conf_dir }}/fluent.conf"
    docker_fluentd_env:
      FLUENTD_GEMS: "fluent-plugin-elasticsearch"
    docker_fluentd_links:
      - "{{ docker_elasticsearch_name }}:elasticsearch"
    docker_fluentd_expose:
      - 24224
    docker_fluentd_ports: []

    docker_scrapi_apiserver_name: "{{ docker_env }}_scrapi_apiserver_1"
    docker_scrapi_apiserver_conf_dir: "/opt/{{ docker_env }}_scrapi_apiserver/conf"
    docker_scrapi_apiserver_env:
      UPDATE_CMD: "invoke wheelhouse && invoke requirements && gosu www-data python manage.py collectstatic --noinput"
      SOURCE_BRANCH: "{{ docker_scrapi_source_branch }}"
      SOURCE_REPO: "{{ docker_scrapi_source_repo }}"
    docker_scrapi_apiserver_links:
      - "{{ docker_elasticsearch_name }}:elasticsearch"
      - "{{ docker_postgres_repmgr_name }}:postgres"
      - "{{ docker_rabbitmq_name }}:rabbitmq"
      - "{{ docker_fluentd_name }}:fluentd"
    docker_scrapi_apiserver_volumes_from:
      - "{{ docker_storage_name }}"

    docker_scrapi_celery_beat_name: "{{ docker_env }}_scrapi_celery_beat"
    docker_scrapi_celery_beat_data_dir: "/opt/{{ docker_env }}_scrapi_celery_beat/data"
    docker_scrapi_celery_beat_links:
      - "{{ docker_elasticsearch_name }}:elasticsearch"
      - "{{ docker_postgres_repmgr_name }}:postgres"
      - "{{ docker_rabbitmq_name }}:rabbitmq"
      - "{{ docker_fluentd_name }}:fluentd"
    docker_scrapi_celery_beat_volumes_from:
      - "{{ docker_storage_name }}"

    docker_scrapi_celery_worker_name: "{{ docker_env }}_scrapi_celery_worker"
    docker_scrapi_celery_worker_hostname: "{{ hostname_name }}"
    docker_scrapi_celery_worker_instances: 1
    docker_scrapi_celery_worker_env:
      SOURCE_BRANCH: "{{ docker_scrapi_source_branch }}"
      SOURCE_REPO: "{{ docker_scrapi_source_repo }}"
    docker_scrapi_celery_worker_expose: []
    docker_scrapi_celery_worker_ports: []
    docker_scrapi_celery_worker_links:
      - "{{ docker_elasticsearch_name }}:elasticsearch"
      - "{{ docker_cassandra_name }}:cassandra"
      - "{{ docker_postgres_repmgr_name }}:postgres"
      - "{{ docker_rabbitmq_name }}:rabbitmq"
      - "{{ docker_fluentd_name }}:fluentd"
    docker_scrapi_celery_worker_volumes_from:
      - "{{ docker_storage_name }}"

    docker_nginx: no
    docker_nginx_name: "{{ docker_env }}_scrapi_nginx_1"
    docker_nginx_image: centerforopenscience/nginx:1 # auto reload on /etc/hosts change
    docker_nginx_conf_dir: "/opt/{{ docker_env }}_scrapi_nginx/conf"
    docker_nginx_expose:
      - 80
      - 443
    docker_nginx_links:
      - "{{ docker_scrapi_apiserver_name }}:apiserver"
    docker_nginx_volumes_from:
      - "{{ docker_storage_name }}"
  roles:
    - role: docker-storage
      when: docker_storage

    - role: docker-cassandra
      when: docker_cassandra

    - role: docker-elasticsearch
      when: docker_elasticsearch

    - role: docker-fluentd
      when: docker_fluentd

    - role: docker-rabbitmq
      when: docker_rabbitmq

    - role: docker-postgres-repmgr
      when: docker_postgres_repmgr

    - role: docker-scrapi

    - role: docker-nginx
      when: docker_nginx
