- name: Set up center for open science
  hosts: all
  pre_tasks:
    - fail: msg="One or more tags must be specified to run this playbook"
  vars:
    docker_storage: no
    docker_storage_name: "{{ docker_env }}_cos_storage_1"
    docker_storage_dir: "/opt/{{ docker_env }}_cos_storage/"
    docker_storage_conf_dir: "{{ docker_storage_dir }}conf/"
    docker_storage_file_ops:
      - state: directory
        path: "{{ docker_storage_dir }}code/"
    docker_storage_volumes:
      - "{{ docker_storage_dir }}code/:/code:rw"

    docker_memcached: no
    docker_memcached_name: "{{ docker_env }}_cos_memcached_1"

    docker_cos_server_name: "{{ docker_env }}_cos_server_1"
    docker_cos_server_conf_dir: "/opt/{{ docker_env }}_cos_server/conf/"
    docker_cos_server_data_dir: "/opt/{{ docker_env }}_cos_server/data/"
    docker_cos_server_links:
      - "{{ docker_memcached_name }}:memcached"
    docker_cos_server_volumes_from:
      - "{{ docker_storage_name }}"

    docker_nginx: no
    docker_nginx_name: "{{ docker_env }}_cos_nginx_1"
    docker_nginx_image: centerforopenscience/nginx:1 # auto reload on /etc/hosts change
    docker_nginx_source_conf_dir: roles/docker-cos/files/nginx/
    docker_nginx_conf_dir: "/opt/{{ docker_env }}_cos_nginx/conf/"
    docker_nginx_expose:
      - 80
      - 443
    docker_nginx_links:
      - "{{ docker_cos_server_name }}:server"
    docker_nginx_volumes_from:
      - "{{ docker_storage_name }}"

  roles:
    - role: docker-storage
      when: docker_storage

    - role: docker-memcached
      when: docker_memcached

    - role: docker-cos

    - role: docker-nginx
      when: docker_nginx
