- name: Setup docker logentries
  hosts: all
  vars:
    docker_fluentd: yes
    docker_fluentd_name: fluentd_1
    docker_fluentd_source_conf_dir: "{{ root_source_conf_dir }}logentries/fluentd/"
    docker_fluentd_conf_dir: /opt/fluentd/conf/
    docker_fluentd_conf_file: "{{ docker_fluentd_conf_dir }}fluent.conf"
    docker_fluentd_data_dir: /opt/fluentd/data/
    docker_fluentd_env:
      FLUENTD_GEMS: "fluent-plugin-order fluent-plugin-record-reformer fluent-plugin-rewrite-tag-filter fluent-plugin-jsonbucket fluent-plugin-docker-format" # fluent-plugin-logentries removed (pr in for fix)
    docker_fluentd_volumes:
      - "{{ docker_fluentd_data_dir }}:/data"
      - "{{ docker_fluentd_conf_dir }}:/etc/fluent:ro"
      - "/var/log/:/var/log:ro"
      - "/var/lib/docker/containers/:/var/lib/docker/containers:ro"
    docker_fluentd_expose:
      - 24224
    docker_fluentd_ports: []
  roles:
    - role: rsyslog
      tags:
        - install

    - role: docker-fluentd
      tags:
        - install
      when: docker_fluentd
