- name: Set up scrapi web/workers
  hosts: all
  pre_tasks:
    - fail: msg="One or more tags must be specified to run this playbook"
  roles:
    - role: swap
    - role: docker
    - role: docker-clean
    - role: docker-scrapi
