
# dotfiles, etc

- name: Collecting facts
  hosts:
    - osf-staging
    - osf-production
  gather_facts: yes

- name: Make sure editors are installed
  hosts: all
  roles:
    - role: editors

- name: Make sure zsh is installed
  hosts: all
  tasks:
    - apt: name=zsh state=present
