
# dotfiles, etc

- name: Make sure editors are installed
  hosts: all
  roles:
    - role: editors

- name: Make sure zsh is installed
  hosts: all
  tasks:
    - apt: name=zsh state=present

- name: "Steve's dotfiles"
  hosts:
    - webservers
    - elasticsearch
    - osf-staging
    - osf-production
  roles:
    - role: dotfiles-sloria
