# file: vagrant.yml

- name: Collecting facts
  hosts: all
  gather_facts: yes

- hosts: all
  roles:
    - role: common
      tags:
        - common
    - role: security
      tags:
        - security
    - role: supervisor
      tags:
        - supervisor
    - role: monit
      tags:
        - monit
