# variables

docker_dor_opt_dir: /opt/dor
docker_dor_log_dir: /var/log/dor


# shared storage

docker_dor_storage_temp: no
docker_dor_storage_temp_name: dor_storage_temp_1
docker_dor_storage_temp_volumes:
  - /tmp


# support servers

docker_dor_postgres: no
docker_dor_postgres_name: dor_postgres_1
docker_dor_postgres_data_dir: /opt/dor-postgres/data
docker_dor_postgres_log_dir: /var/log/dor-postgres
docker_dor_postgres_env:
  POSTGRES_DB: dor_staging
docker_dor_postgres_expose:
  - 5432
docker_dor_postgres_ports: []


# servers

docker_dor_uwsgi: no
docker_dor_uwsgi_name: dor_uwsgi_1
docker_dor_uwsgi_image: centerforopenscience/dor:latest
docker_dor_uwsgi_source_branch: develop
docker_dor_uwsgi_source_repo: https://github.com/mfraezz/DirectoryOfRepositories.git
docker_dor_uwsgi_source_conf_file: uwsgi.ini
docker_dor_uwsgi_source_app_file: local.py
docker_dor_uwsgi_conf_dir: "{{ docker_dor_opt_dir }}/conf"
docker_dor_uwsgi_conf_file: "{{ docker_dor_uwsgi_conf_dir }}/uwsgi.ini"
docker_dor_uwsgi_app_file: "{{ docker_dor_uwsgi_conf_dir }}/local.py"
docker_dor_uwsgi_log_dir: "{{ docker_dor_log_dir }}"
docker_dor_uwsgi_env:
  SOURCE_BRANCH: "{{ docker_dor_uwsgi_source_branch }}"
  SOURCE_REPO: "{{ docker_dor_uwsgi_source_repo }}"
docker_dor_uwsgi_expose:
  - 8080
docker_dor_uwsgi_ports: []
docker_dor_uwsgi_links:
  - "{{ docker_dor_postgres_name }}:postgres"
docker_dor_uwsgi_volumes:
  - "{{ docker_dor_uwsgi_conf_file }}:/etc/uwsgi/uwsgi.ini"
  - "{{ docker_dor_uwsgi_app_file }}:/home/.cos/local.py"
  - "{{ docker_dor_uwsgi_log_dir }}:/log"
docker_dor_uwsgi_volumes_from:
  - "{{ docker_dor_storage_temp_name }}"


docker_dor_nginx: no
docker_dor_nginx_name: dor_nginx_1
docker_dor_nginx_image: centerforopenscience/nginx:latest
docker_dor_nginx_source_conf_file: nginx.conf
docker_dor_nginx_source_ssl_crt_file: ""
docker_dor_nginx_source_ssl_key_file: ""
docker_dor_nginx_conf_dir: "{{ docker_dor_opt_dir }}/conf"
docker_dor_nginx_conf_file: "{{ docker_dor_nginx_conf_dir }}/nginx.conf"
docker_dor_nginx_log_dir: "{{ docker_dor_log_dir }}"
docker_dor_nginx_env: {}
docker_dor_nginx_expose:
  - 80
  - 443
docker_dor_nginx_ports: []
docker_dor_nginx_links:
  - "{{ docker_dor_uwsgi_name }}:uwsgi"
docker_dor_nginx_volumes:
  - "{{ docker_dor_nginx_conf_file }}:/etc/nginx/sites-templates/default.conf.tmpl"
  - "{{ docker_dor_nginx_log_dir }}:/var/log/nginx"
docker_dor_nginx_volumes_from:
  - "{{ docker_dor_uwsgi_name }}"
  - "{{ docker_dor_storage_temp_name }}"
