- name: Ensure docker rabbitmq directories exist
  sudo: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_rabbitmq_data_dir }}"
  tags:
    - install
    - upgrade


- name: Restart docker rabbitmq container
  sudo: yes
  shell: "docker restart {{ docker_rabbitmq_name }}"
  tags:
    - restart


- name: Run docker rabbitmq container
  docker:
    env: "{{ docker_rabbitmq_env }}"
    hostname: "{{ hostname_name }}"
    image: rabbitmq:latest
    name: "{{ docker_rabbitmq_name }}"
    pull: always
    restart_policy: always
    state: reloaded
    volumes:
      - "{{ docker_rabbitmq_data_dir }}:/var/lib/rabbitmq"
  tags:
    - install
    - upgrade
