---

- name: Make sure git is installed
  apt: name=git state=present

- name: Get github.com RSA key
  sudo: False
  shell: ssh-keyscan -t rsa github.com
  connection: local
  register: rsaresult
  changed_when: False
  failed_when: "rsaresult.rc != 0"

- name: Ensure github.com key in /etc/ssh/ssh_known_hosts
  sudo: True
  lineinfile:
    line="{{ rsaresult.stdout }}"
    dest="/etc/ssh/ssh_known_hosts"
    insertafter=EOF
    create=yes
    state=present
    mode=0777
