docker_nginx_name: nginx_1
docker_nginx_source_conf_file: nginx.conf
docker_nginx_env: {}
docker_nginx_conf_dir: /opt/nginx/conf
docker_nginx_conf_file: "{{ docker_nginx_conf_dir }}/nginx.conf"
docker_nginx_log_dir: /var/log/nginx
docker_nginx_links: []
docker_nginx_volumes:
  - "{{ docker_nginx_conf_file }}:/etc/nginx/nginx.conf:ro"
  - "{{ docker_nginx_log_dir }}:/var/log/nginx"
