# variables

docker_share_reg_env: test


# shared storage

docker_share_reg_storage: no
docker_share_reg_storage_name: "{{ docker_share_reg_env }}_share_reg_storage_1"
docker_share_reg_storage_volumes:
  - /tmp
  - /code


# support servers

docker_share_reg_postgres: no
docker_share_reg_postgres_name: "{{ docker_share_reg_env }}_share_reg_postgres_1"
docker_share_reg_postgres_data_dir: "/opt/{{ docker_share_reg_env }}_share_reg_postgres/data"
docker_share_reg_postgres_env:
  POSTGRES_DB: share_registration
docker_share_reg_postgres_expose:
  - 5432
docker_share_reg_postgres_ports: []

docker_share_reg_nginx: no
docker_share_reg_nginx_name: "{{ docker_share_reg_env }}_share_reg_nginx_1"
docker_share_reg_nginx_image: nginx:1
docker_share_reg_nginx_source_confd_dir: conf.d/
docker_share_reg_nginx_source_ssl_dir: roles/docker-nginx/files/ssl/
docker_share_reg_nginx_conf_dir: "/opt/{{ docker_share_reg_env }}_share_reg_nginx/conf"
docker_share_reg_nginx_confd_dir: "{{ docker_share_reg_nginx_conf_dir }}/conf.d"
docker_share_reg_nginx_ssl_dir: "{{ docker_share_reg_nginx_conf_dir }}/ssl"
docker_share_reg_nginx_env: {}
docker_share_reg_nginx_expose:
  - 80
  - 443
docker_share_reg_nginx_ports: []
docker_share_reg_nginx_links: []
docker_share_reg_nginx_volumes:
  - "{{ docker_share_reg_nginx_confd_dir }}:/etc/nginx/conf.d:ro"
  - "{{ docker_share_reg_nginx_ssl_dir }}:/etc/ssl/private:ro"
docker_share_reg_nginx_volumes_from:
  - "{{ docker_share_reg_storage_name }}"


# servers

docker_share_reg_uwsgi: no
docker_share_reg_uwsgi_name: "{{ docker_share_reg_env }}_share_reg_uwsgi_1"
docker_share_reg_uwsgi_image: centerforopenscience/share-reg:latest
docker_share_reg_uwsgi_source_branch: master
docker_share_reg_uwsgi_source_repo: https://github.com/erinspace/shareregistration.git
docker_share_reg_uwsgi_source_conf_file: uwsgi.ini
docker_share_reg_uwsgi_source_app_file: local.py
docker_share_reg_uwsgi_conf_dir: "/opt/{{ docker_share_reg_env }}_share_reg_uwsgi/conf"
docker_share_reg_uwsgi_conf_file: "{{ docker_share_reg_uwsgi_conf_dir }}/uwsgi.ini"
docker_share_reg_uwsgi_app_file: "{{ docker_share_reg_uwsgi_conf_dir }}/local.py"
docker_share_reg_uwsgi_env:
  SOURCE_BRANCH: "{{ docker_share_reg_uwsgi_source_branch }}"
  SOURCE_REPO: "{{ docker_share_reg_uwsgi_source_repo }}"
docker_share_reg_uwsgi_expose: []
docker_share_reg_uwsgi_ports: []
docker_share_reg_uwsgi_links:
  - "{{ docker_share_reg_postgres_name }}:postgres"
docker_share_reg_uwsgi_volumes:
  - "{{ docker_share_reg_uwsgi_conf_file }}:/etc/uwsgi/uwsgi.ini"
  - "{{ docker_share_reg_uwsgi_app_file }}:/home/.cos/local.py"
docker_share_reg_uwsgi_volumes_from:
  - "{{ docker_share_reg_storage_name }}"
