# shared storage

docker_share_reg_storage_temp: no
docker_share_reg_storage_temp_name: share_reg_storage_temp_1
docker_share_reg_storage_temp_volumes:
  - /tmp


# support servers

docker_share_reg_postgres: no
docker_share_reg_postgres_name: share_reg_postgres_1
docker_share_reg_postgres_data_dir: /opt/share-reg-postgres/data
docker_share_reg_postgres_log_dir: /var/log/share-reg-postgres
docker_share_reg_postgres_log_rotate_file: share-reg-postgres
docker_share_reg_postgres_env:
  POSTGRES_DB: share_registration
docker_share_reg_postgres_expose:
  - 5432
docker_share_reg_postgres_ports: []


# servers

docker_share_reg_uwsgi: no
docker_share_reg_uwsgi_name: share_reg_uwsgi_1
docker_share_reg_uwsgi_image: centerforopenscience/share:registration
docker_share_reg_uwsgi_source_branch: develop
docker_share_reg_uwsgi_source_repo: https://github.com/erinspace/shareregistration.git
docker_share_reg_uwsgi_source_conf_file: uwsgi.ini
docker_share_reg_uwsgi_source_app_file: local.py
docker_share_reg_uwsgi_conf_dir: "/opt/share-reg-uwsgi/conf"
docker_share_reg_uwsgi_conf_file: "{{ docker_share_reg_uwsgi_conf_dir }}/uwsgi.ini"
docker_share_reg_uwsgi_app_file: "{{ docker_share_reg_uwsgi_conf_dir }}/local.py"
docker_share_reg_uwsgi_log_dir: "/var/log/share-reg"
docker_share_reg_uwsgi_env:
  SOURCE_BRANCH: "{{ docker_share_reg_uwsgi_source_branch }}"
  SOURCE_REPO: "{{ docker_share_reg_uwsgi_source_repo }}"
docker_share_reg_uwsgi_expose: []
docker_share_reg_uwsgi_ports: []
docker_share_reg_uwsgi_links:
  - "{{ docker_share_postgres_name }}:postgres"
docker_share_reg_uwsgi_volumes:
  - "{{ docker_share_reg_uwsgi_conf_file }}:/etc/uwsgi/uwsgi.ini"
  - "{{ docker_share_reg_uwsgi_app_file }}:/home/.cos/local.py"
  - "{{ docker_share_reg_uwsgi_log_dir }}:/log"
docker_share_reg_uwsgi_volumes_from:
  - "{{ docker_share_reg_storage_temp_name }}"


docker_share_reg_nginx: no
docker_share_reg_nginx_name: share_reg_nginx_1
docker_share_reg_nginx_image: centerforopenscience/nginx:latest
docker_share_reg_nginx_source_conf_file: nginx.conf
docker_share_reg_nginx_source_ssl_crt_file: ""
docker_share_reg_nginx_source_ssl_key_file: ""
docker_share_reg_nginx_conf_dir: "/opt/share-reg-nginx/conf"
docker_share_reg_nginx_conf_file: "{{ docker_share_reg_nginx_conf_dir }}/nginx.conf"
docker_share_reg_nginx_log_dir: "/var/log/share-reg-nginx"
docker_share_reg_nginx_env: {}
docker_share_reg_nginx_expose:
  - 80
  - 443
docker_share_reg_nginx_ports: []
docker_share_reg_nginx_links: []
docker_share_reg_nginx_volumes:
  - "{{ docker_share_reg_nginx_conf_file }}:/etc/nginx/sites-templates/default.conf.tmpl"
  - "{{ docker_share_reg_nginx_log_dir }}:/var/log/nginx"
docker_share_reg_nginx_volumes_from:
  - "{{ docker_share_reg_uwsgi_name }}"
  - "{{ docker_share_reg_storage_temp_name }}"
