- name: Restart docker fluentd container
  sudo: yes
  shell: "docker restart {{ docker_fluentd_name }}"
  tags:
    - restart


- name: Ensure docker fluentd directories exist
  sudo: yes
  file:
    state: directory
    path: "{{ docker_fluentd_conf_dir }}"
  tags:
    - install
    - upgrade


- name: Copy docker fluentd configuration settings
  copy:
    src: "{{ docker_fluentd_source_conf_file }}"
    dest: "{{ docker_fluentd_conf_file }}"
    mode: 0644
  tags:
    - install
    - settings
    - upgrade


- name: Run docker fluentd container
  docker:
    env: "{{ docker_fluentd_env }}"
    expose: "{{ docker_fluentd_expose }}"
    hostname: "{{ hostname_name }}-fluentd"
    links: "{{ docker_fluentd_links }}"
    image: "centerforopenscience/fluentd:latest"
    name: "{{ docker_fluentd_name }}"
    ports: "{{ docker_fluentd_ports }}"
    restart_policy: always
    state: running
    volumes:
      - "{{ docker_fluentd_conf_file }}:/etc/fluent/fluent.conf"
  tags:
    - install
    - upgrade
