- name: Ensure docker fluentd logrotate config
  template:
    src: "{{ docker_fluentd_logrotate_source_file }}"
    dest: "/etc/logrotate.d/{{ docker_fluentd_logrotate_file }}"
    owner: root
    group: root
    mode: 0644
  tags:
    - install
    - settings


- name: Ensure docker fluentd directories exist
  sudo: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_fluentd_conf_dir }}"
    - "{{ docker_fluentd_log_dir }}"
  tags:
    - install
    - upgrade


- name: Copy docker fluentd configuration settings
  copy:
    src: "{{ docker_fluentd_source_conf_dir }}"
    dest: "{{ docker_fluentd_conf_dir }}"
    mode: 0644
  tags:
    - install
    - settings
    - upgrade


- name: Restart docker fluentd container
  sudo: yes
  shell: "docker restart {{ docker_fluentd_name }}"
  tags:
    - restart


- name: Run docker fluentd container
  docker:
    env: "{{ docker_fluentd_env }}"
    expose: "{{ docker_fluentd_expose }}"
    hostname: "{{ hostname_name }}"
    links: "{{ docker_fluentd_links }}"
    image: "{{ docker_fluentd_image }}"
    name: "{{ docker_fluentd_name }}"
    # net: host
    ports: "{{ docker_fluentd_ports }}"
    pull: always
    restart_policy: always
    state: reloaded
    volumes: "{{ docker_fluentd_volumes }}"
  tags:
    - install
    - upgrade
