docker_logentries_fluentd: no
docker_logentries_fluentd_name: fluentd_1
docker_logentries_fluentd_source_conf_dir: roles/docker-logentries/files/fluentd/
docker_logentries_fluentd_conf_dir: "/opt/fluentd/conf"
docker_logentries_fluentd_conf_file: "{{ docker_logentries_fluentd_conf_dir }}/fluent.conf"
docker_logentries_fluentd_data_dir: "/opt/fluentd/data"
docker_logentries_fluentd_env:
  FLUENTD_GEMS: "fluent-plugin-order fluent-plugin-record-reformer fluent-plugin-rewrite-tag-filter fluent-plugin-jsonbucket fluent-plugin-docker-format" # fluent-plugin-logentries removed (pr in for fix)
docker_logentries_fluentd_volumes:
  - "{{ docker_logentries_fluentd_data_dir }}:/data"
  - "{{ docker_logentries_fluentd_conf_dir }}:/etc/fluent:ro"
  - "/var/log:/var/log:ro"
  - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
