- name: Ensure docker storage directories exist
  sudo: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items: docker_storage_dirs
  tags:
    - install
    - upgrade


- name: Run docker storage container
  docker:
    image: busybox:latest
    name: "{{ docker_storage_name }}"
    volumes: "{{ docker_storage_volumes }}"
  tags:
    - install
    - upgrade
