dependencies:
  - role: docker-storage
    docker_storage_name: "{{ docker_osf_storage_name }}"
    docker_storage_volumes: "{{ docker_osf_storage_volumes }}"
    when: docker_osf_storage

  - role: docker-elasticsearch
    docker_elasticsearch_name: "{{ docker_osf_elasticsearch_name }}"
    docker_elasticsearch_source_conf_dir: "{{ docker_osf_elasticsearch_source_conf_dir }}"
    docker_elasticsearch_conf_dir: "{{ docker_osf_elasticsearch_conf_dir }}"
    docker_elasticsearch_data_dir: "{{ docker_osf_elasticsearch_data_dir }}"
    docker_elasticsearch_env: "{{ docker_osf_elasticsearch_env }}"
    docker_elasticsearch_net: "{{ docker_osf_elasticsearch_net }}"
    docker_elasticsearch_hostname: "{{ docker_osf_elasticsearch_hostname }}"
    docker_elasticsearch_expose: "{{ docker_osf_elasticsearch_expose }}"
    docker_elasticsearch_ports: "{{ docker_osf_elasticsearch_ports }}"
    when: docker_osf_elasticsearch

  - role: docker-nginx
    docker_nginx_name: "{{ docker_osf_elasticsearch_nginx_name }}"
    docker_nginx_image: "{{ docker_osf_elasticsearch_nginx_image }}"
    docker_nginx_source_ssl_dir: "{{ docker_osf_elasticsearch_nginx_source_ssl_dir }}"
    docker_nginx_source_conf_file: "{{ docker_osf_elasticsearch_nginx_source_conf_file }}"
    docker_nginx_source_htpasswd_file: "{{ docker_osf_elasticsearch_nginx_source_htpasswd_file }}"
    docker_nginx_conf_dir: "{{ docker_osf_elasticsearch_nginx_conf_dir }}"
    docker_nginx_env: "{{ docker_osf_elasticsearch_nginx_env }}"
    docker_nginx_net: "{{ docker_osf_elasticsearch_nginx_net }}"
    docker_nginx_hostname: "{{ docker_osf_elasticsearch_nginx_hostname }}"
    docker_nginx_links: "{{ docker_osf_elasticsearch_nginx_links }}"
    docker_nginx_expose: "{{ docker_osf_elasticsearch_nginx_expose }}"
    docker_nginx_ports: "{{ docker_osf_elasticsearch_nginx_ports }}"
    when: docker_osf_elasticsearch_nginx

  - role: docker-tokumx
    docker_tokumx_name: "{{ docker_osf_tokumx_name }}"
    docker_tokumx_conf_dir: "{{ docker_osf_tokumx_conf_dir }}"
    docker_tokumx_data_dir: "{{ docker_osf_tokumx_data_dir }}"
    docker_tokumx_env: "{{ docker_osf_tokumx_env }}"
    docker_tokumx_net: "{{ docker_osf_tokumx_net }}"
    docker_tokumx_hostname: "{{ docker_osf_tokumx_hostname }}"
    docker_tokumx_expose: "{{ docker_osf_tokumx_expose }}"
    docker_tokumx_ports: "{{ docker_osf_tokumx_ports }}"
    when: docker_osf_tokumx

  - role: docker-nginx
    docker_nginx_name: "{{ docker_osf_tokumx_nginx_name }}"
    docker_nginx_image: "{{ docker_osf_tokumx_nginx_image }}"
    docker_nginx_source_ssl_dir: "{{ docker_osf_tokumx_nginx_source_ssl_dir }}"
    docker_nginx_source_conf_file: "{{ docker_osf_tokumx_nginx_source_conf_file }}"
    docker_nginx_source_htpasswd_file: "{{ docker_osf_tokumx_nginx_source_htpasswd_file }}"
    docker_nginx_conf_dir: "{{ docker_osf_tokumx_nginx_conf_dir }}"
    docker_nginx_env: "{{ docker_osf_tokumx_nginx_env }}"
    docker_nginx_net: "{{ docker_osf_tokumx_nginx_net }}"
    docker_nginx_hostname: "{{ docker_osf_tokumx_nginx_hostname }}"
    docker_nginx_links: "{{ docker_osf_tokumx_nginx_links }}"
    docker_nginx_expose: "{{ docker_osf_tokumx_nginx_expose }}"
    docker_nginx_ports: "{{ docker_osf_tokumx_nginx_ports }}"
    when: docker_osf_tokumx_nginx
