# varaibles

docker_mfr_env: test


# shared storage

docker_mfr_storage_temp: no
docker_mfr_storage_temp_name: mfr_storage_temp_1
docker_mfr_storage_temp_volumes:
  - /tmp


# support servers

docker_mfr_unoconv: no
docker_mfr_unoconv_name: mfr_unoconv_1
docker_mfr_unoconv_log_dir: "/var/log/mfr-unoconv"
docker_mfr_unoconv_volumes:
  - "{{ docker_mfr_unoconv_log_dir }}:/log"
  - /tmp
docker_mfr_unoconv_volumes_from:
  - "{{ docker_mfr_storage_temp_name }}"


# servers

docker_mfr_web: no
docker_mfr_web_name: mfr_web
docker_mfr_web_image: centerforopenscience/mfr:latest
docker_mfr_web_log_dir: "/var/log/mfr-web"
docker_mfr_web_source_branch: develop
docker_mfr_web_source_repo: https://github.com/CenterForOpenScience/modular-file-renderer.git
docker_mfr_web_source_conf_file: "mfr-{{ docker_mfr_env }}.json"
docker_mfr_web_conf_dir: "/opt/mfr-web/conf"
docker_mfr_web_conf_file: "{{ docker_mfr_web_conf_dir }}/mfr-{{ docker_mfr_env }}.json"
docker_mfr_web_ssl_cert_file: ""
docker_mfr_web_ssl_key_file: ""
docker_mfr_web_cert_src: ""
docker_mfr_web_instances: 2
docker_mfr_web_start_port: 7770
docker_mfr_web_env:
  ENV: "{{ docker_mfr_env }}"
  SOURCE_BRANCH: "{{ docker_mfr_web_source_branch }}"
  SOURCE_REPO: "{{ docker_mfr_web_source_repo }}"
docker_mfr_web_volumes:
  - "{{ docker_mfr_web_conf_file }}:/home/.cos/mfr-{{ docker_mfr_env }}.json"
  - "{{ docker_mfr_web_conf_dir }}/ssl:/home/.cos/ssl"
  - "{{ docker_mfr_web_log_dir }}:/log"
  - /tmp
docker_mfr_web_volumes_from:
  - "{{ docker_mfr_storage_temp_name }}"
docker_mfr_web_links:
  - "{{ docker_mfr_unoconv_name }}:unoconv"
docker_mfr_web_expose:
  - 7778
docker_mfr_web_ports:
  - "{{ (docker_mfr_web_start_port | int) + (item | int) - 1 }}:7778"
