dependencies:
  - role: docker-storage
    docker_storage_name: "{{ docker_dor_storage_name }}"
    docker_storage_volumes: "{{ docker_dor_storage_volumes }}"
    when: docker_dor_storage

  - role: docker-postgres
    docker_postgres_name: "{{ docker_dor_postgres_name }}"
    docker_postgres_data_dir: "{{ docker_dor_postgres_data_dir }}"
    docker_postgres_env: "{{ docker_dor_postgres_env }}"
    docker_postgres_expose: "{{ docker_dor_postgres_expose }}"
    docker_postgres_ports: "{{ docker_dor_postgres_ports }}"
    when: docker_dor_postgres

  - role: docker-nginx
    docker_nginx_name: "{{ docker_dor_nginx_name }}"
    docker_nginx_image: "{{ docker_dor_nginx_image }}"
    docker_nginx_source_conf_file: "{{ docker_dor_nginx_source_conf_file }}"
    docker_nginx_source_ssl_dir: "{{ docker_dor_nginx_source_ssl_dir }}"
    docker_nginx_conf_dir: "{{ docker_dor_nginx_conf_dir }}"
    docker_nginx_conf_file: "{{ docker_dor_nginx_conf_file }}"
    docker_nginx_ssl_dir: "{{ docker_dor_nginx_ssl_dir }}"
    docker_nginx_env: "{{ docker_dor_nginx_env }}"
    docker_nginx_expose: "{{ docker_dor_nginx_expose }}"
    docker_nginx_ports: "{{ docker_dor_nginx_ports }}"
    docker_nginx_links: "{{ docker_dor_nginx_links }}"
    docker_nginx_volumes: "{{ docker_dor_nginx_volumes }}"
    docker_nginx_volumes_from: "{{ docker_dor_nginx_volumes_from }}"
    when: docker_dor_nginx
