- name: Restart docker postgres container
  sudo: yes
  shell: "docker restart {{ docker_postgres_name }}"
  tags:
    - restart


- name: Ensure docker postgres directories exist
  sudo: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_postgres_data_dir }}"
  tags:
    - install
    - upgrade


- name: Run docker postgres container
  docker:
    name: "{{ docker_postgres_name }}"
    state: running
    hostname: "{{ hostname_name }}-postgres"
    restart_policy: always
    env: "{{ docker_postgres_env }}"
    image: "postgres:9"
    volumes: "{{ docker_postgres_volumes }}"
  tags:
    - install
    - upgrade
