- name: Restart docker waterbutler celery container
  sudo: yes
  shell: "docker restart {{ docker_waterbutler_celery_name }}_{{ item }}"
  with_sequence: count={{ docker_waterbutler_celery_instances }}
  when: docker_waterbutler_celery_instances > 0
  tags:
    - restart


- name: Run docker waterbutler celery container
  docker:
    command: '/bin/bash -c "invoke celery 2>&1 | tee -a /log/{{ docker_waterbutler_celery_name }}_{{ item }}.log"'
    env: "{{ docker_waterbutler_celery_env }}"
    expose: "{{ docker_waterbutler_celery_expose }}"
    hostname: "{{ hostname_name }}-celery{{ item }}"
    image: "centerforopenscience/waterbutler:latest"
    links: "{{ docker_waterbutler_celery_links }}"
    name: "{{ docker_waterbutler_celery_name }}_{{ item }}"
    ports: "{{ docker_waterbutler_celery_ports }}"
    restart_policy: always
    state: running
    volumes: "{{ docker_waterbutler_celery_volumes }}"
    volumes_from: "{{ docker_waterbutler_celery_volumes_from }}"
  with_sequence: count={{ docker_waterbutler_celery_instances }}
  when: docker_waterbutler_celery_instances > 0
  tags:
    - install
    - upgrade
