- name: Ensure docker waterbutler logrotate config
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/waterbutler
    owner: root
    group: root
    mode: 0644
  tags:
    - install
    - settings


- name: Ensure docker waterbutler directories exist
  sudo: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_waterbutler_conf_dir }}"
    - "{{ docker_waterbutler_conf_dir }}/ssl"
    - "{{ docker_waterbutler_log_dir }}"
    - "{{ docker_waterbutler_osfstorage_pending_dir }}"
    - "{{ docker_waterbutler_osfstorage_complete_dir }}"
  tags:
    - install
    - upgrade


- name: Copy docker waterbutler configuration settings
  copy:
    src: "{{ docker_waterbutler_source_conf_file }}"
    dest: "{{ docker_waterbutler_conf_file }}"
    mode: 0660
  tags:
    - install
    - settings
    - upgrade


- name: Copy docker waterbutler ssl certificate file
  copy:
    mode: 0640
    src: "{{ docker_waterbutler_server_ssl_cert_file }}"
    dest: "{{ docker_waterbutler_conf_dir }}/ssl/default.crt"
  when: docker_waterbutler_server_ssl_cert_file | default("") != ""
  tags:
    - install
    - settings
    - upgrade


- name: Copy docker waterbutler ssl key file
  copy:
    mode: 0640
    src: "{{ docker_waterbutler_server_ssl_key_file }}"
    dest: "{{ docker_waterbutler_conf_dir }}/ssl/default.key"
  when: docker_waterbutler_server_ssl_key_file | default("") != ""
  tags:
    - install
    - settings
    - upgrade
