- name: Ensure docker waterbutler common directories exist
  sudo: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_waterbutler_osfstorage_pending_dir }}"
    - "{{ docker_waterbutler_osfstorage_complete_dir }}"
  tags:
    - install
    - upgrade
