- name: Restart docker waterbutler server container
  sudo: yes
  shell: "docker restart {{ docker_waterbutler_server_name }}_{{ item }}"
  with_sequence: count={{ docker_waterbutler_server_instances }}
  when: docker_waterbutler_server_instances > 0
  tags:
    - restart


- name: Run docker waterbutler server container
  docker:
    command: '/bin/bash -c "invoke server 2>&1 | tee -a /log/{{ docker_waterbutler_server_name }}_{{ item }}.log"'
    env: "{{ docker_waterbutler_server_env }}"
    expose: "{{ docker_waterbutler_server_expose }}"
    hostname: "{{ hostname_name }}-server{{ item }}"
    image: "centerforopenscience/waterbutler:latest"
    links: "{{ docker_waterbutler_server_links }}"
    name: "{{ docker_waterbutler_server_name }}_{{ item }}"
    ports: "{{ docker_waterbutler_server_ports }}"
    restart_policy: always
    state: running
    volumes: "{{ docker_waterbutler_server_volumes }}"
    volumes_from: "{{ docker_waterbutler_server_volumes_from }}"
  with_sequence: count={{ docker_waterbutler_server_instances }}
  when: docker_waterbutler_server_instances > 0
  tags:
    - install
    - upgrade
