- name: Run docker waterbutler temporary storage container
  docker:
    image: busybox:latest
    name: "{{ docker_waterbutler_storage_temp_name }}"
    volumes: "{{ docker_waterbutler_storage_temp_volumes }}"
  when: docker_waterbutler_storage_temp
  tags:
    - install
    - upgrade
