- name: Ensure docker osf server uwsgi directories exist
  sudo: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_osf_server_uwsgi_conf_dir }}"
    - "{{ docker_osf_server_uwsgi_website_conf_dir }}"
  tags:
    - install
    - upgrade


- name: Copy docker osf server uwsgi configuration settings
  copy:
    src: "{{ docker_osf_server_uwsgi_source_conf_file }}"
    dest: "{{ docker_osf_server_uwsgi_conf_file }}"
    mode: 0644
  tags:
    - install
    - settings
    - upgrade


- name: Copy docker of server uwsgi website configuration settings
  copy:
    src: "{{ docker_osf_server_uwsgi_source_website_conf_dir }}"
    dest: "{{ docker_osf_server_uwsgi_website_conf_dir }}"
    mode: 0644
  tags:
    - install
    - settings
    - upgrade


- name: Restart docker osf server uwsgi container
  sudo: yes
  shell: "docker restart {{ docker_osf_server_uwsgi_name }}"
  tags:
    - restart


- name: Run docker osf server uwsgi container
  docker:
    command: "uwsgi --ini /etc/uwsgi/uwsgi.ini"
    env: "{{ docker_osf_server_uwsgi_env }}"
    expose: "{{ docker_osf_server_uwsgi_expose }}"
    hostname: "{{ docker_osf_server_uwsgi_hostname }}"
    image: "{{ docker_osf_server_uwsgi_image }}"
    links: "{{ docker_osf_server_uwsgi_links }}"
    name: "{{ docker_osf_server_uwsgi_name }}"
    net: "{{ docker_osf_server_uwsgi_net }}"
    ports: "{{ docker_osf_server_uwsgi_ports }}"
    pull: always
    restart_policy: always
    state: reloaded
    volumes: "{{ docker_osf_server_uwsgi_volumes }}"
    volumes_from: "{{ docker_osf_server_uwsgi_volumes_from }}"
  tags:
    - install
    - upgrade
