docker_osf_celery_name: osf_celery
docker_osf_celery_instances: 1

docker_osf_server_name: osf_server
docker_osf_server_instances: 1

docker_osf_conf_dir: /opt/osf/conf
docker_osf_data_dir: /opt/osf/data
docker_osf_mfrcache_dir: /opt/osf/mfrcache
docker_osf_mfrctemp_dir: /opt/osf/mfrtemp
docker_osf_log_dir: /var/log/osf

docker_osf_sharejs_name: osf_sharejs_1

docker_osf_elasticsearch_name: osf_elasticsearch_1
docker_osf_elasticsearch_conf_dir: "{{ docker_osf_conf_dir }}/elasticsearch"
docker_osf_elasticsearch_data_dir: "{{ docker_osf_data_dir }}/elasticsearch"
docker_osf_elasticsearch_log_dir: "{{ docker_osf_log_dir }}/elasticsearch"

docker_osf_rabbitmq_name: osf_rabbitmq_1
docker_osf_rabbitmq_dir: "{{ docker_osf_data_dir }}/rabbitmq"

docker_osf_tokumx_name: osf_tokumx_1
docker_osf_tokumx_conf_file: "{{ docker_osf_conf_dir }}/tokumx.conf"
docker_osf_tokumx_data_dir: "{{ docker_osf_data_dir }}/tokumx"
docker_osf_tokumx_log_dir: "{{ docker_osf_log_dir }}/tokumx"
