# variables

docker_osf_env: test


# shared storage

docker_osf_storage: no
docker_osf_storage_name: "{{ docker_osf_env }}_osf_storage_1"
docker_osf_storage_volumes:
  - /tmp


# support servers

docker_osf_elasticsearch: no
docker_osf_elasticsearch_name: "{{ docker_osf_env }}_osf_elasticsearch_1"
docker_osf_elasticsearch_source_conf_dir: roles/docker-elasticsearch/files/conf/
docker_osf_elasticsearch_conf_dir: "/opt/{{ docker_osf_env }}_osf_elasticsearch/conf"
docker_osf_elasticsearch_data_dir: "/opt/{{ docker_osf_env }}_osf_elasticsearch/data"
docker_osf_elasticsearch_env:
  ES_HEAP_SIZE: "{{ (ansible_memtotal_mb / 2) | int }}m"
docker_osf_elasticsearch_net: bridge
docker_osf_elasticsearch_hostname: "{{ hostname_name }}"
docker_osf_elasticsearch_expose:
  - 9200
  - 9300
docker_osf_elasticsearch_ports: []

docker_osf_elasticsearch_nginx: no
docker_osf_elasticsearch_nginx_name: "{{ docker_osf_env }}_osf_elasticsearch_nginx_1"
docker_osf_elasticsearch_nginx_image: centerforopenscience/nginx:1 # allow for environment variables in nginx.conf
docker_osf_elasticsearch_nginx_source_conf_file: elasticsearch/nginx.conf
docker_osf_elasticsearch_nginx_source_htpasswd_file: elasticsearch/.htpasswd
docker_osf_elasticsearch_nginx_source_ssl_dir: roles/docker-nginx/files/ssl/
docker_osf_elasticsearch_nginx_conf_dir: "/opt/{{ docker_osf_env }}_osf_elasticsearch_nginx/conf"
docker_osf_elasticsearch_nginx_env: {}
docker_osf_elasticsearch_nginx_net: bridge
docker_osf_elasticsearch_nginx_hostname: "{{ hostname_name }}"
docker_osf_elasticsearch_nginx_links:
  - "{{ docker_osf_elasticsearch_name }}:elasticsearch"
docker_osf_elasticsearch_nginx_expose:
  - 9243
  - 9343
docker_osf_elasticsearch_nginx_ports: []

docker_osf_tokumx: no
docker_osf_tokumx_name: "{{ docker_osf_env }}_osf_tokumx_1"
docker_osf_tokumx_source_conf_dir: roles/docker-tokumx/files/conf/
docker_osf_tokumx_conf_dir: "/opt/{{ docker_osf_env }}_osf_tokumx/conf"
docker_osf_tokumx_data_dir: "/opt/{{ docker_osf_env }}_osf_tokumx/data"
docker_osf_tokumx_env: {}
docker_osf_tokumx_net: bridge
docker_osf_tokumx_hostname: "{{ hostname_name }}"
docker_osf_tokumx_expose:
  - 27017
  - 28017
docker_osf_tokumx_ports: []


# servers

docker_osf_nginx: no
docker_osf_nginx_volumes_from:
  - "{{ docker_osf_storage }}"

docker_osf_uwsgi: no
docker_osf_uwsgi_links:
  - "{{ docker_osf_elasticsearch_nginx_name }}:elasticsearch"
docker_osf_uwsgi_volumes_from:
  - "{{ docker_osf_storage }}"
