- name: Ensure docker postgres repmgr logrotate config
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/postgres
    owner: root
    group: root
    mode: 0644
  tags:
    - install
    - settings


- name: Restart docker postgres repmgr container
  sudo: yes
  shell: "docker restart {{ docker_postgres_repmgr_name }}"
  tags:
    - restart


- name: Ensure docker postgres repmgr directories exist
  sudo: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_postgres_repmgr_conf_dir }}"
    - "{{ docker_postgres_repmgr_data_dir }}"
    - "{{ docker_postgres_repmgr_log_dir }}"
  tags:
    - install
    - upgrade


- name: Copy repmgr configuration settings
  copy:
    src: "{{ docker_postgres_repmgr_source_conf_file }}"
    dest: "{{ docker_postgres_repmgr_conf_file }}"
    mode: 0644
  tags:
    - install


- name: Run docker postgres repmgr container
  docker:
    name: "{{ docker_postgres_repmgr_name }}"
    image: centerforopenscience/postgres:9.4-repmgr
    state: running
    hostname: "{{ docker_postgres_repmgr_hostname }}"
    restart_policy: always
    net: "{{ docker_postgres_repmgr_net }}"
    env: "{{ docker_postgres_repmgr_env }}"
    links: "{{ docker_postgres_repmgr_links }}"
    expose: "{{ docker_postgres_repmgr_expose }}"
    ports: "{{ docker_postgres_repmgr_ports }}"
    volumes: "{{ docker_postgres_repmgr_volumes }}"
  tags:
    - install
    - upgrade
