- name: Restart docker postgres repmgr container
  sudo: yes
  shell: "docker restart {{ docker_postgres_repmgr_name }}"
  tags:
    - restart


- name: Ensure docker postgres repmgr directories exist
  sudo: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_postgres_repmgr_conf_dir }}"
    - "{{ docker_postgres_repmgr_data_dir }}"
  tags:
    - install
    - upgrade


- name: Copy repmgr configuration settings
  copy:
    src: "{{ docker_postgres_repmgr_source_conf_file }}"
    dest: "{{ docker_postgres_repmgr_conf_file }}"
    mode: 0644
  tags:
    - install


- name: Run docker postgres repmgr container
  docker:
    env: "{{ docker_postgres_repmgr_env }}"
    expose: "{{ docker_postgres_repmgr_expose }}"
    hostname: "{{ docker_postgres_repmgr_hostname }}"
    image: "{{ docker_postgres_repmgr_image }}"
    links: "{{ docker_postgres_repmgr_links }}"
    name: "{{ docker_postgres_repmgr_name }}"
    net: "{{ docker_postgres_repmgr_net }}"
    ports: "{{ docker_postgres_repmgr_ports }}"
    pull: always
    restart_policy: always
    state: reloaded
    volumes: "{{ docker_postgres_repmgr_volumes }}"
  tags:
    - install
    - upgrade
