dependencies:
  - role: docker-storage
    docker_storage_name: "{{ docker_mfr_storage_name }}"
    docker_storage_volumes: "{{ docker_mfr_storage_volumes }}"
    when: docker_mfr_storage

  - role: docker-unoconv
    docker_unoconv_name: "{{ docker_mfr_unoconv_name }}"
    docker_unoconv_volumes: "{{ docker_mfr_unoconv_volumes }}"
    docker_unoconv_volumes_from: "{{ docker_mfr_unoconv_volumes_from }}"
    docker_unoconv: "{{ docker_mfr_unoconv }}"
