- name: Install csf-started.conf in upstart
  sudo: yes
  copy:
    src: csf-docker-wait.conf
    dest: /etc/init/csf-docker-wait.conf
    mode: 0644
  tags:
    - install

- name: Upgrade CSF
  sudo: yes
  command: csf -u
  tags:
    - csf_upgrade


- name: Restart machine
  command: shutdown -r now "Restart CSF and Docker"
  async: 0
  poll: 0
  ignore_errors: true
  tags:
    - install
    - csf_upgrade


- name: Waiting for server to come back
  local_action:
    wait_for
    host={{ inventory_hostname }}
    state=started
    port=22
  sudo: false
  tags:
    - install
    - csf_upgrade
