# variables
docker_cas_source_branch: master
docker_cas_source_repo: https://github.com/CenterForOpenScience/cas-overlay.git

# servers

docker_cas_server: no
docker_cas_server_image: centerforopenscience/cas:4.1
docker_cas_server_definitions: "-Dproject.parent.basedir=/etc/cas"
docker_cas_server_source_conf_dir: etc
docker_cas_server_conf_dir: /opt/cas_server/conf/
docker_cas_server_hostname: "{{ hostname_name }}"
docker_cas_server_name: "cas_server_1"
docker_cas_server_net: bridge
docker_cas_server_env:
  SOURCE_BRANCH: "{{ docker_cas_source_branch }}"
  SOURCE_REPO: "{{ docker_cas_source_repo }}"
  CAS_DB_USERNAME: postgres
  CAS_DB_PASSWORD:
  OSF_DB_PORT_27017_TCP_ADDR: 127.0.0.1
  OSF_DB_PORT_27017_TCP_PORT: 27017
  OSF_DB_NAME: osf20130903
docker_cas_server_expose:
  - 8080
  - 8443
docker_cas_server_ports: []
docker_cas_server_links: []
docker_cas_server_volumes:
  - "{{ docker_cas_server_conf_dir }}:/etc/cas"
