# variables

docker_cas_env: test

# support servers

docker_cas_postgres: no
docker_cas_postgres_source_conf_file: repmgr.conf
docker_cas_postgres_conf_dir: "/opt/{{ docker_cas_env }}_cas_postgres/conf"
docker_cas_postgres_conf_file: "{{ docker_cas_postgres_conf_dir }}/repmgr.conf"
docker_cas_postgres_data_dir: "/opt/{{ docker_cas_env }}_cas_postgres/data"
docker_cas_postgres_db_name: cas
docker_cas_postgres_name: "{{ docker_cas_env }}_cas_postgres_1"
docker_cas_postgres_hostname: "{{ hostname_name }}"
docker_cas_postgres_net: bridge
docker_cas_postgres_env:
  POSTGRES_DB: "{{ docker_cas_postgres_db_name }}"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
docker_cas_postgres_expose: []
docker_cas_postgres_ports: []
docker_cas_postgres_links: []
docker_cas_postgres_volumes:
  - "{{ docker_cas_postgres_conf_file }}:/etc/repmgr/repmgr.conf"
  - "{{ docker_cas_postgres_data_dir }}:/var/lib/postgresql/data"


# servers

docker_cas_server: no
docker_cas_server_source_branch: master
docker_cas_server_image: centerforopenscience/cas:4.1
docker_cas_server_source_repo: https://github.com/CenterForOpenScience/cas-overlay.git
docker_cas_server_definitions: "-Dproject.parent.basedir=/etc/cas"
docker_cas_server_source_conf_dir: etc
docker_cas_server_conf_dir: /opt/{{ docker_cas_env }}_cas_server/conf
docker_cas_server_hostname: "{{ hostname_name }}"
docker_cas_server_name: "{{ docker_cas_env }}_cas_server_1"
docker_cas_server_net: bridge
docker_cas_server_env:
  SOURCE_BRANCH: "{{ docker_cas_server_source_branch }}"
  SOURCE_REPO: "{{ docker_cas_server_source_repo }}"
  CAS_DB_USERNAME: postgres
  CAS_DB_PASSWORD:
  OSF_DB_PORT_27017_TCP_ADDR: 127.0.0.1
  OSF_DB_PORT_27017_TCP_PORT: 27017
  OSF_DB_NAME: osf20130903
docker_cas_server_expose: []
docker_cas_server_ports: []
docker_cas_server_links:
  - "{{ docker_cas_postgres_name }}:cas_db"
docker_cas_server_volumes:
  - "{{ docker_cas_server_conf_dir }}:/etc/cas"
