- name: Ensure docker log rotate config
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/docker
    owner: root
    group: root
    mode: 0644
  tags:
    - install
    - settings


- name: Update APT package cache
  apt: update_cache=yes
  sudo: yes
  tags:
    - install


- name: Install docker system dependencies
  sudo: yes
  apt:
    state: latest
    pkg: python-pip
  tags:
    - install


- name: Force pip upgrade
  sudo: yes
  shell: easy_install -U pip
  tags:
    - install


- name: Install docker apt keys
  sudo: yes
  apt_key:
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9
    keyserver: "hkp://keyserver.ubuntu.com:80"
    state: present
  tags:
    - install


- name: Install docker apt repository
  sudo: yes
  apt_repository:
    repo: "deb https://get.docker.com/ubuntu docker main"
    state: present
  tags:
    - install


- name: Install docker pip dependencies (v1.7)
  sudo: yes
  pip:
    state: latest
    name: "{{ item }}"
  with_items:
    - "docker-py==1.2.3"
    - "python-apt"
  tags:
    - v1.7


- name: Install docker (v1.7)
  sudo: yes
  apt:
    state: latest
    pkg: "lxc-docker-1.7.1"
  tags:
    - v1.7


# Stuck on v1.5 when needing to mount a single file.
# issue: https://github.com/ansible/ansible-modules-core/issues/1158
# pull: https://github.com/ansible/ansible-modules-core/pull/1744
- name: Install docker pip dependencies (v1.5)
  sudo: yes
  pip:
    state: latest
    name: "{{ item }}"
  with_items:
    - "docker-py==1.1.0"
    - "python-apt"
  tags:
    - v1.5


- name: Install docker (v1.5)
  sudo: yes
  apt:
    state: latest
    pkg: "lxc-docker-1.5.0"
  tags:
    - v1.5


- name: Restart docker
  sudo: yes
  service:
    name: docker
    state: restarted
  tags:
    - install
