- name: Ensure docker log rotate config
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/docker
    owner: root
    group: root
    mode: 0644
  tags:
    - install
    - settings


- name: Update APT package cache
  apt: update_cache=yes
  sudo: yes
  tags:
    - install


- name: Install docker system dependencies
  sudo: yes
  apt:
    state: latest
    pkg: python-pip
  tags:
    - install


- name: Force pip upgrade
  sudo: yes
  shell: easy_install -U pip
  tags:
    - install


- name: Install docker pip dependencies
  sudo: yes
  pip:
    state: latest
    name: "{{ item }}"
  with_items:
    - "docker-py==1.2.3" # docker 1.7.0 compatible
    # - "docker-py==1.2.2" # docker 1.6.0 compatible
    # - "docker-py==1.1.0" # docker 1.5.0 compatible
    # - "docker-py==0.7.2" # docker 1.4.1 compatible
    - "python-apt"
  tags:
    - install


- name: Install docker apt keys
  sudo: yes
  apt_key:
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9
    keyserver: "hkp://keyserver.ubuntu.com:80"
    state: present
  tags:
    - install


- name: Install docker apt repository
  sudo: yes
  apt_repository:
    repo: "deb https://get.docker.com/ubuntu docker main"
    state: present
  tags:
    - install


- name: Install docker
  sudo: yes
  apt:
    state: latest
    pkg: "lxc-docker-1.7.1"
    # pkg: "lxc-docker-1.6.0"
    # pkg: "lxc-docker-1.5.0"
    # pkg: "lxc-docker-1.4.1"
  tags:
    - install


- name: Restart docker
  sudo: yes
  service:
    name: docker
    state: restarted
  tags:
    - install
