# CSF checks


- name: test csf | Enable testing mode
  lineinfile: dest=/etc/csf/csf.conf regexp="^TESTING\s?=" line='TESTING="1"' state=present
  tags:
    - csf
    - testing
  changed_when: false

- name: test csf | csf restart
  command: csf -r
  sudo: yes
  changed_when: false


- name: test csf | Port scans are denied
  connection: local
  sudo: no
  # doalarm runs a command and returns an error if no output was captured in
  # {{check_portscan_timeout}} seconds
  # Here, a portscan is attempted; CSF should hang the connection, so doalarm() should
  # return an error
  shell: doalarm () { perl -e 'alarm shift; exec @ARGV' "$@"; } && doalarm {{check_portscan_timeout}} nc -z {{item}} 1-1023
  when: check_portscan
  with_items: check_portscan_hosts
  # If the above portscan command succeeded (return code 0), then csf is not denying port scans!
  register: portscan_result
  failed_when: "portscan_result.rc == 0"


- name: test csf | Disable testing mode
  lineinfile: dest=/etc/csf/csf.conf regexp="^TESTING\s?=" line='TESTING="0"' state=present
  changed_when: false

- name: test csf | csf restart
  command: csf -r
  sudo: yes
  changed_when: false

# Check csf configuration
# For some reason, csf logs configuration errors to stdout, so fail when the
# word "error" is found in stdout
- name: check csf configuration
  command: csf -c
  register: csf_conf_check
  failed_when: "'error' in csf_conf_check.stdout.lower()"
