# CSF checks


- name: Enable testing mode
  lineinfile: dest=/etc/csf/csf.conf regexp="^TESTING\s?=" line='TESTING="1"' state=present
  tags:
    - csf
    - testing

- name: csf restart
  shell: csf -r
  sudo: yes

# TODO: Test CSF

- name: Disable testing mode
  lineinfile: dest=/etc/csf/csf.conf regexp="^TESTING\s?=" line='TESTING="0"' state=present
  tags:
    - csf

- name: csf restart
  shell: csf -r
  sudo: yes
