- name: Install sendmail
  apt: pkg={{ item }}
  sudo: yes
  register: install_sendmail
  with_items:
    - sendmail-bin
    - sendmail

- name: Install libwww-perl
  apt: pkg=libwww-perl
  sudo: yes
  register: install_libwww
