
# Install dependencies
- include: deps.yml

- name: csf | Check if csf exists
  stat: path=/usr/local/csf/bin/csftest.pl
  sudo: yes
  register: check_path

- get_url: url=http://www.configserver.com/free/csf.tgz dest=/tmp/
  when: check_path.stat.exists == false

- shell: tar -xzf /tmp/csf.tgz -C /tmp/
  when: check_path.stat.exists == false

- shell: ufw disable
  sudo: yes
  when: check_path.stat.exists == false

- name: csf | install
  shell: cd /tmp/csf/; sh install.sh
  sudo: yes
  when: check_path.stat.exists == false

- name: Test if csf is working
  shell: perl /usr/local/csf/bin/csftest.pl
  sudo: yes
  register: check_contents
  failed_when: check_contents.stdout.find("csf should function on this server") == -1

- name: copy conf
  template: src=csf.conf.j2 dest=/etc/csf/csf.conf
  sudo: yes


- name: copy csf.allow
  template: src=csf.allow.j2 dest=/etc/csf/csf.allow
  sudo: yes

- name: copy ui.allow
  template: src=ui.allow.j2 dest=/etc/csf/ui/ui.allow
  sudo: yes

- name: csf enable
  shell: csf -e
  sudo: yes

- name: csf restart
  shell: csf -r
  sudo: yes

- name: lfd restart
  service: name=lfd state=restarted
  sudo: yes

