osf_apps_dir: "/opt/apps/"

osf_repo_dir: "{{osf_apps_dir}}osf/"

# Where to put virtualenvs
# Must have trailing slash
osf_virtualenvs_dir: "/opt/envs/"

# Location of the osf virtualenv
osf_virtualenv: "{{osf_virtualenvs_dir}}osf/"

# The branch to check out
osf_repo_branch: master

osf_env_vars:
    - {var: "OSF_PRODUCTION", val: "0"}
    - {var: "OSF_STAGING", val: "1"}


# UWSGI ini vars
# The place for uwsgi to create the sock file
osf_uwsgi_socket: /tmp/osf.sock
osf_uwsgi_processes: 4
osf_uwsgi_threads: 2
osf_uwsgi_harakiri: 60
osf_uwsgi_buffersize: 8192
