- name: Ensure docker mfr logrotate config
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/mfr
    owner: root
    group: root
    mode: 0644
  tags:
    - install
    - settings


- name: Ensure docker mfr directories exist
  sudo: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_mfr_conf_dir }}"
    - "{{ docker_mfr_conf_dir }}/ssl"
    - "{{ docker_mfr_log_dir }}"
    - "{{ docker_mfr_localcache_dir }}"
  tags:
    - install
    - upgrade


- name: Copy docker mfr configuration settings
  copy:
    src: "{{ docker_mfr_source_conf_file }}"
    dest: "{{ docker_mfr_conf_file }}"
    mode: 0660
  tags:
    - install
    - settings
    - upgrade


- name: Copy docker mfr ssl certificate file
  copy:
    mode: 0640
    src: "{{ docker_mfr_server_ssl_cert_file }}"
    dest: "{{ docker_mfr_conf_dir }}/ssl/default.crt"
  when: docker_mfr_server_ssl_cert_file | default("") != ""
  tags:
    - install
    - settings
    - upgrade


- name: Copy docker mfr ssl key file
  copy:
    mode: 0640
    src: "{{ docker_mfr_server_ssl_key_file }}"
    dest: "{{ docker_mfr_conf_dir }}/ssl/default.key"
  when: docker_mfr_server_ssl_key_file | default("") != ""
  tags:
    - install
    - settings
    - upgrade
