- name: Restart docker mfr server container
  sudo: yes
  shell: "docker restart {{ docker_mfr_server_name }}_{{ item }}"
  with_sequence: count={{ docker_mfr_server_instances }}
  when: docker_mfr_server_instances > 0
  tags:
    - restart


- name: Run docker mfr server container
  docker:
    command: '/bin/bash -c "invoke server 2>&1 | tee -a /log/{{ docker_mfr_server_name }}_{{ item }}.log"'
    env: "{{ docker_mfr_server_env }}"
    expose: "{{ docker_mfr_server_expose }}"
    hostname: "{{ hostname_name }}-server{{ item }}"
    image: "{{ docker_mfr_server_image }}"
    links: "{{ docker_mfr_server_links }}"
    name: "{{ docker_mfr_server_name }}_{{ item }}"
    ports: "{{ docker_mfr_server_ports }}"
    restart_policy: always
    state: running
    volumes: "{{ docker_mfr_server_volumes }}"
    volumes_from: "{{ docker_mfr_server_volumes_from }}"
  with_sequence: count={{ docker_mfr_server_instances }}
  when: docker_mfr_server_instances > 0
  tags:
    - install
    - upgrade
