- name: secure linode
  hosts: "{{host}}"
  remote_user: "{{user}}"
  gather_facts: True
  roles:
    - ../roles/csf
#    - apt
#    - ansible
#    - nginx

#
#
#
#    - name: Install required packages
#      action: apt pkg={{item}} state=installed
#      with_items:
#        - emacs24
#        - git # not git-core; renamed
#        - wget
#
#    - include: csf/csf.yml
##    - include: denyhosts/denyhosts.yml
#
#

#  handlers:
#    - include: denyhosts/handlers.yml
#    - include: csf/handlers.yml
#    - name: restart ssh
#      service: name=ssh state=restarted
