# variables
docker_waterbutler_source_branch: develop
docker_waterbutler_source_repo: https://github.com/CenterForOpenScience/waterbutler.git
docker_waterbutler_osfstorage_pending_dir: "/opt/waterbutler_osfstorage/pending"
docker_waterbutler_osfstorage_complete_dir: "/opt/waterbutler_osfstorage/complete"

# celery
docker_waterbutler_celery: no
docker_waterbutler_celery_name: waterbutler_celery
docker_waterbutler_celery_image: centerforopenscience/waterbutler:latest
docker_waterbutler_celery_command: "invoke celery --hostname=worker{{ item }}.%h"
docker_waterbutler_celery_hostname: "{{ hostname_name }}"
docker_waterbutler_celery_instances: 1
docker_waterbutler_celery_env:
  ENV: "{{ docker_env | default('test') }}"
  SOURCE_BRANCH: "{{ docker_waterbutler_source_branch }}"
  SOURCE_REPO: "{{ docker_waterbutler_source_repo }}"
docker_waterbutler_celery_net: bridge
docker_waterbutler_celery_expose: []
docker_waterbutler_celery_ports: []
docker_waterbutler_celery_links:
  - "{{ docker_waterbutler_rabbitmq_name }}:rabbitmq"
docker_waterbutler_celery_volumes: []
docker_waterbutler_celery_volumes_from: []

# server
docker_waterbutler_server: no
docker_waterbutler_server_name: waterbutler_server
docker_waterbutler_server_image: centerforopenscience/waterbutler:latest
docker_waterbutler_server_command: invoke server
docker_waterbutler_server_hostname: "{{ hostname_name }}"
docker_waterbutler_server_instances: 2
docker_waterbutler_server_source_ssl_dir: ssl/
docker_waterbutler_server_conf_dir: /opt/waterbutler_server/conf
docker_waterbutler_server_ssl_dir: "{{ docker_waterbutler_server_conf_dir }}ssl/"
docker_waterbutler_server_start_port: 7770
docker_waterbutler_server_env:
  ENV: "{{ docker_env | default('test') }}"
  SOURCE_BRANCH: "{{ docker_waterbutler_source_branch }}"
  SOURCE_REPO: "{{ docker_waterbutler_source_repo }}"
docker_waterbutler_server_net: bridge
docker_waterbutler_server_links: []
docker_waterbutler_server_expose:
  - 7777
docker_waterbutler_server_ports: []
docker_waterbutler_server_volumes:
  - "{{ docker_waterbutler_server_ssl_dir }}:/home/.cos/ssl:ro"
docker_waterbutler_server_volumes_from: []
