docker_haproxy_name: haproxy_1
docker_haproxy_env: {}
docker_haproxy_conf_dir: /opt/haproxy/conf

docker_haproxy_rsyslog_name: rsyslog_1
docker_haproxy_rsyslog_conf_dir: "{{ docker_haproxy_conf_dir }}/rsyslog"
docker_haproxy_rsyslog_log_dir: /var/log/haproxy

docker_haproxy_enable_https: false
docker_haproxy_default_cert_src: ""
# docker_haproxy_default_cert_src: "{{ '~/.cos/ssl/default.pem' | expanduser }}"
docker_haproxy_certsd_dir_src: ""

docker_haproxy_stats_user: User1
docker_haproxy_stats_password: password

# docker_haproxy_backends:
#   - name: my_domain
#     domain: my.domain.com
#     servers:
#       - ip: "192.168.1.2"
#         port: 1111
#       - ip: "192.168.1.2"
#         port: 1112
#       - ip: "192.168.1.6"
#         port: 1111
#       - ip: "192.168.1.6"
#         port: 1112
