# openvpn

docker_openvpn_name: openvpn_1
docker_openvpn_image: centerforopenscience/openvpn
docker_openvpn_net: bridge
docker_openvpn_hostname: "{{ hostname_name }}"
docker_openvpn_privileged: no
docker_openvpn_volumes: []
docker_openvpn_volumes_from: []
