- name: Delete all docker containers
  sudo: yes
  shell: "docker rm -f $(docker ps -aq)"
  ignore_errors: yes
  tags:
    - clean
    - upgrade


- name: Delete all docker images
  sudo: yes
  shell: "docker rmi -f $(docker images -q)"
  ignore_errors: yes
  tags:
    - clean
